{% set name = "SVT-AV1" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/AOMediaCodec/{{ name|lower }}/-/archive/v{{ version }}/{{ name|lower }}-v{{ version }}.tar.gz
  sha256: 084720e7818cec7cb38d31ab478478b910d643fe5b13fc2cfcbd9da9c9d5c84b

build:
  number: 0
  run_exports:
    # This is just a guess
    - {{ pin_subpackage('svt-av1', max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - yasm

test:
  commands:
    - test -f ${PREFIX}/include/svt-av1/EbSvtAv1.h          # [unix]
    - test -f ${PREFIX}/lib/libSvtAv1Enc${SHLIB_EXT}        # [unix]
    - if not exist %LIBRARY_BIN%\SvtAv1Enc.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\svt-av1/EbSvtAv1.h exit 1  # [win]
    - SvtAv1EncApp --help  # [unix and build_platform == target_platform]

about:
  home: https://gitlab.com/AOMediaCodec/SVT-AV1
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The Scalable Video Technology for AV1 encoder/decoder library.
  description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder) is an
    AV1-compliant encoder/decoder library core.
  dev_url: https://gitlab.com/AOMediaCodec/SVT-AV1
  doc_url: https://gitlab.com/AOMediaCodec/SVT-AV1

extra:
  recipe-maintainers:
    - matthiasdiener
